server:
  port: 6060


mvc:
  servlet:
    load-on-startup: 100

token:
  ddf9e65b-2d89-4f67-9afe-7d8b80a65c82
AppCode:
  9887772c6590460e94f2bf8aae34891a
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.shangpin.entity
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml
#日志打印文件
logging:
  file:
    name: ../shangpin_log/log.log
  level:
    com:
      shangpin: debug

## 数据源配置
spring:
  http:
    encoding:
      force: true
    # redis 配置
  datasource:
    #测试
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.41.201:3306/shangpin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123
